title: Colour a snowman
hero_image: images/banner.png
description: Learn how to colour in a 3D model of a snowman using Blender.
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: ""
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Colour the hat
