title: Colour a snowman
hero_image: images/banner.png
description: Learn how to colour in a 3D model of a snowman using Blender
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-01-28
steps: 
- title: Introduction
- title: Colour the hat
- title: Colour an eye
- title: Colour the eyes and buttons
- title: Colour the nose
- title: "Challenge: colour the body"
